setup: &setup
  adapter: postgresql
  username: saddacracker
  password:

development:
  <<: *setup
  database: shared_todo_app_dev
  host: localhost
  encoding: UTF8

test:
  <<: *setup
  database: shared_todo_app_test

staging:
  <<: *setup
  database: shared_todo_app_st

production:
  <<: *setup
  database: shared_todo_app_prod

